// Punkt I (26.09.): gemeinsame Quelle der Plattform-Fakten.
//  - PLATFORM_FACTS: das Array in Format_Dev_Payload (an Dev_Frontend, Dev_Backend, Feedback-Loop und QA_Gatekeeper)
//  - PO_PLATFORM_SECTION: Abschnitt "# PLATFORM CONSTRAINTS" im Systemprompt des Product Owner; enthält alle
//    PLATFORM_FACTS wörtlich (je Zeile "- <fakt>") plus die Plattform-Grenzen und Regeln, die NUR der PO bekommt
//    (Marcs Entscheidung 26.09.: fester Stack, Dateiumfang, festes Dockerfile, keine Env-Variablen nur im PO-Teil).
//  - checkDrift(fdpCode, poPrompt): Drift-Prüfung zwischen beiden Stellen (Offline-Test, Live-Patch vor/nach dem PUT).
// Patch- und Testskripte verwenden ausschließlich dieses Modul (Muster wie compliance_pattern_patch.js).

// Die 7 Fakten aus Punkt 14 (live seit 24.09. 21:16:04Z), byte-gleich zum Live-Code.
const FACTS_PUNKT_14 = [
  "Same origin: index.html and the API are served by the same FastAPI app on the same port. Do not add CORSMiddleware.",
  "main.py serves index.html at GET / via FileResponse(Path(__file__).parent / 'index.html') (from pathlib import Path; from fastapi.responses import FileResponse). Never embed HTML in main.py. GET / must answer with a status below 400.",
  "The frontend calls only the specified API routes with relative paths (e.g. fetch('/api/...')). It never mocks, intercepts or overrides fetch and never fabricates API data in the browser.",
  "API data and user input reach the DOM only via textContent, createElement or .value; innerHTML only for static markup.",
  "No polling (setInterval/refresh loops) unless the specification explicitly asks for live updates.",
  "Python route handlers use 'async def' or 'def'.",
  "The app runs in Docker as 'uvicorn main:app --host 0.0.0.0 --port 8000'; host and port are fixed by the container.",
];
// 8. Fakt (Marcs Freigabe 26.09.)
const FACT_OVERRIDE = "platform_facts override any conflicting specification item.";
const PLATFORM_FACTS = [...FACTS_PUNKT_14, FACT_OVERRIDE];

const PO_FACTS_INTRO = "Platform facts (passed verbatim to the developer and QA agents as platform_facts; your specification must never contradict them):";

const PO_PLATFORM_SECTION = [
  "# PLATFORM CONSTRAINTS (fixed, not negotiable)",
  "Every app is generated by a fixed pipeline and deployed on a fixed platform. Your specification and every option you offer must fit it.",
  "",
  "Fixed platform:",
  "- Stack: FastAPI (Python 3.11) backend + one single index.html (HTML5 + Vanilla JS + Tailwind CSS via CDN). No other language, framework or build step (no Node.js/Express, React, Vue, npm, TypeScript).",
  "- Files: exactly main.py, requirements.txt and index.html (README.md and .env.example are added automatically). No further source files (no app.js, styles.css, templates/, static/, config.py).",
  "- Deployment: the pipeline writes its own fixed Dockerfile (python:3.11-slim) and runs one container per app. No own Dockerfile, no docker-compose, no reverse proxy or HTTPS setup.",
  "- Configuration: the container starts without environment variables or secrets; the app must run with built-in defaults. No external services (no PostgreSQL, Redis, SMTP, message queues).",
  "- Data: in-memory, or a SQLite file inside the container. A SQLite file does not survive a redeploy (no volume).",
  "",
  PO_FACTS_INTRO,
  ...PLATFORM_FACTS.map(f => "- " + f),
  "",
  "Rules for you:",
  "- Never offer options outside the platform (e.g. Node.js instead of FastAPI, an own Docker setup). \"2 concrete options\" means two options within the platform (e.g. in-memory vs. SQLite file).",
  "- If the user asks for something outside the platform (e.g. Node.js, React, CORS, docker-compose, environment configuration), say so openly in DISCOVERY: name the limit in one sentence and offer the platform solution. Never drop, replace or ignore such a wish silently.",
  "- If you offer SQLite, state that the database file does not survive a redeploy (no volume).",
  "- Never specify CORS/CORSMiddleware, StaticFiles mounts, Jinja2 templates or HTML embedded in main.py, neither in developer_spec nor as a qa_spec check. index.html is served at GET / via FileResponse.",
  "",
].join('\n');

// Code-Block in Format_Dev_Payload (Kommentar + Array), erzeugt aus PLATFORM_FACTS.
function factsCode(facts, comment) {
  return [comment, "const PLATFORM_FACTS = [", ...facts.map(f => "  " + JSON.stringify(f) + ","), "];", ""].join('\n');
}
const FDP_COMMENT_OLD = "// Punkt H (24.09.): Plattform-Fakten – einzige Quelle für Dev_Frontend, Dev_Backend und QA_Gatekeeper";
const FDP_COMMENT_NEW = "// Punkt H (24.09.) / Punkt I (26.09.): Plattform-Fakten für Dev_Frontend, Dev_Backend und QA_Gatekeeper.\n" +
  "// Quelle: platform_facts.js. Wörtliche Kopie im Product-Owner-Prompt (# PLATFORM CONSTRAINTS), Drift-Test: test_po_facts_offline.js";
const FDP_BLOCK_OLD = factsCode(FACTS_PUNKT_14, FDP_COMMENT_OLD);
const FDP_BLOCK_NEW = factsCode(PLATFORM_FACTS, FDP_COMMENT_NEW);

// PLATFORM_FACTS aus einem Format_Dev_Payload-Code lesen: Code ausführen (Stub-Eingabe) und das Ausgabefeld nehmen.
async function factsFromFdpCode(code) {
  const AsyncFunction = Object.getPrototypeOf(async function () {}).constructor;
  const fn = new AsyncFunction('$', '$input', '$json', 'Buffer', code);
  const out = await fn(() => { throw new Error('$() im Stub nicht verfügbar'); }, { all: () => [] }, { output: '{"project_name":"Drift Probe"}' }, Buffer);
  return out[0].json.platform_facts;
}
// Fakten-Block aus dem PO-Prompt lesen: Zeilen "- ..." direkt nach PO_FACTS_INTRO bis zur ersten Leerzeile.
function factsFromPoPrompt(prompt) {
  const i = prompt.indexOf(PO_FACTS_INTRO + '\n');
  if (i === -1) return null;
  const lines = prompt.slice(i + PO_FACTS_INTRO.length + 1).split('\n');
  const out = [];
  for (const l of lines) { if (!l.startsWith('- ')) break; out.push(l.slice(2)); }
  return out;
}
// Drift-Prüfung: beide Stellen müssen exakt PLATFORM_FACTS (Reihenfolge, Bytes, Anzahl) enthalten.
async function checkDrift(fdpCode, poPrompt) {
  const problems = [];
  let fdp;
  try { fdp = await factsFromFdpCode(fdpCode); } catch (e) { problems.push('Format_Dev_Payload nicht ausführbar: ' + e.message); }
  const po = factsFromPoPrompt(poPrompt);
  if (!po) problems.push('PO-Prompt: Fakten-Block (Einleitungssatz) fehlt');
  const cmp = (label, arr) => {
    if (!Array.isArray(arr)) { problems.push(label + ': keine Fakten gelesen'); return; }
    if (arr.length !== PLATFORM_FACTS.length) problems.push(`${label}: ${arr.length} Fakten statt ${PLATFORM_FACTS.length}`);
    PLATFORM_FACTS.forEach((f, k) => { if (arr[k] !== f) problems.push(`${label}: Fakt ${k + 1} weicht ab`); });
  };
  if (fdp !== undefined) cmp('Format_Dev_Payload', fdp);
  if (po) cmp('PO-Prompt', po);
  if (Array.isArray(fdp) && po && JSON.stringify(fdp) !== JSON.stringify(po)) problems.push('Format_Dev_Payload und PO-Prompt unterschiedlich');
  return problems;
}

module.exports = { FACTS_PUNKT_14, FACT_OVERRIDE, PLATFORM_FACTS, PO_FACTS_INTRO, PO_PLATFORM_SECTION, FDP_BLOCK_OLD, FDP_BLOCK_NEW, factsFromFdpCode, factsFromPoPrompt, checkDrift };
